name: "Server Deployment"
on:
  push:
    branches: [master]

jobs: 
  deployment:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Say Hello!
    run: echo "Hello are you there!"

